ALTER POLICY "crud-authenticated-policy-select" ON "meal_options" TO authenticated USING ("meal_options"."tenant_id" = current_setting('app.current_tenant_id', true)::uuid);--> statement-breakpoint
ALTER POLICY "crud-authenticated-policy-insert" ON "meal_options" TO authenticated WITH CHECK ("meal_options"."tenant_id" = current_setting('app.current_tenant_id',true)::uuid);--> statement-breakpoint
ALTER POLICY "crud-authenticated-policy-update" ON "meal_options" TO authenticated USING ("meal_options"."tenant_id" = current_setting('app.current_tenant_id',true)::uuid) WITH CHECK ("meal_options"."tenant_id" = current_setting('app.current_tenant_id',true)::uuid);--> statement-breakpoint
ALTER POLICY "crud-authenticated-policy-delete" ON "meal_options" TO authenticated USING ("meal_options"."tenant_id" = current_setting('app.current_tenant_id',true)::uuid);--> statement-breakpoint
ALTER POLICY "crud-authenticated-policy-select" ON "opportunities" TO authenticated USING ("opportunities"."tenant_id" = current_setting('app.current_tenant_id', true)::uuid);--> statement-breakpoint
ALTER POLICY "crud-authenticated-policy-insert" ON "opportunities" TO authenticated WITH CHECK ("opportunities"."tenant_id" = current_setting('app.current_tenant_id', true)::uuid);--> statement-breakpoint
ALTER POLICY "crud-authenticated-policy-update" ON "opportunities" TO authenticated USING ("opportunities"."tenant_id" = current_setting('app.current_tenant_id', true)::uuid) WITH CHECK ("opportunities"."tenant_id" = current_setting('app.current_tenant_id', true)::uuid);--> statement-breakpoint
ALTER POLICY "crud-authenticated-policy-delete" ON "opportunities" TO authenticated USING ("opportunities"."tenant_id" = current_setting('app.current_tenant_id', true)::uuid);--> statement-breakpoint
ALTER POLICY "crud-authenticated-policy-select" ON "sign_ups" TO authenticated USING ("sign_ups"."tenant_id" = current_setting('app.current_tenant_id', true)::uuid);--> statement-breakpoint
ALTER POLICY "crud-authenticated-policy-insert" ON "sign_ups" TO authenticated WITH CHECK ("sign_ups"."tenant_id" = current_setting('app.current_tenant_id', true)::uuid);--> statement-breakpoint
ALTER POLICY "crud-authenticated-policy-update" ON "sign_ups" TO authenticated USING ("sign_ups"."tenant_id" = current_setting('app.current_tenant_id', true)::uuid) WITH CHECK ("sign_ups"."tenant_id" = current_setting('app.current_tenant_id', true)::uuid);--> statement-breakpoint
ALTER POLICY "crud-authenticated-policy-delete" ON "sign_ups" TO authenticated USING ("sign_ups"."tenant_id" = current_setting('app.current_tenant_id', true)::uuid);--> statement-breakpoint
ALTER POLICY "crud-authenticated-policy-select" ON "tenants" TO authenticated USING ("tenants"."id" = current_setting('app.current_tenant_id', true)::uuid);--> statement-breakpoint
ALTER POLICY "crud-authenticated-policy-insert" ON "tenants" TO authenticated WITH CHECK ("tenants"."id" = current_setting('app.current_tenant_id', true)::uuid);--> statement-breakpoint
ALTER POLICY "crud-authenticated-policy-update" ON "tenants" TO authenticated USING ("tenants"."id" = current_setting('app.current_tenant_id', true)::uuid) WITH CHECK ("tenants"."id" = current_setting('app.current_tenant_id', true)::uuid);--> statement-breakpoint
ALTER POLICY "crud-authenticated-policy-delete" ON "tenants" TO authenticated USING ("tenants"."id" = current_setting('app.current_tenant_id', true)::uuid);--> statement-breakpoint
ALTER POLICY "crud-authenticated-policy-select" ON "users" TO authenticated USING ("users"."tenant_id" = current_setting('app.current_tenant_id', true)::uuid);--> statement-breakpoint
ALTER POLICY "crud-authenticated-policy-insert" ON "users" TO authenticated WITH CHECK ("users"."tenant_id" = current_setting('app.current_tenant_id', true)::uuid);--> statement-breakpoint
ALTER POLICY "crud-authenticated-policy-update" ON "users" TO authenticated USING ("users"."tenant_id" = current_setting('app.current_tenant_id', true)::uuid) WITH CHECK ("users"."tenant_id" = current_setting('app.current_tenant_id', true)::uuid);--> statement-breakpoint
ALTER POLICY "crud-authenticated-policy-delete" ON "users" TO authenticated USING ("users"."tenant_id" = current_setting('app.current_tenant_id', true)::uuid);